[project]
name = "pcd-prac-01"
version = "0.1.0"
description = "Práctica de PCD de Joaquin y Makar"
readme = "README.md"
authors = [
    { name = "Joaquin", email = "joaquin.negrete@alumnos.upm.es" },
    { name = "Makar Isaev", email = "m.isaev@alumnos.upm.es" }
]
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
    "mlxtend>=0.25.0",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
]
